miky_admin_bot:
    resource: "@MikyBotBundle/Resources/config/routing/back.yml"
    prefix : /%miky_admin.admin_path%

miky_app_bot:
    resource: "@MikyBotBundle/Resources/config/routing/front.yml"
    prefix : /bot

miky_api_bot:
    resource: "@MikyBotBundle/Resources/config/routing/api.yml"

