<?php

namespace Miky\Bundle\BotBundle\Repository;

/**
 * PortRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortRepository extends \Doctrine\ORM\EntityRepository
{
}
